### ISSUE TITLE
EM algorithm failed: Estimation of gamma coefficients failed due to non-finite cluster probabilities.

### ISSUE THREAD

**Issue by vrodriguezf** [helske/seqHMM#41]
Hi!

I am having the error:
`EM algorithm failed: Estimation of gamma coefficients failed due to non-finite cluster probabilities.`
when training some MHMMs in my experiment. I am making a blind search of the best MHMM across diferrent possibilities of number of clusters and number of states, and this error appears only in a few of the models. What can I do to avoid it?

Thanks!

**Comment by helske** [comment]
There are several reasons why this can happen, but most likely it is because at some point during the search you are trying to fit too poor model (or with poor initial values) to the data, leading to issues with coefficients of mixture probabilities. It could be that optimization finds a degenerate case where all the sequences end up in a single cluster, or one cluster doesn't contain any cases, or the matrix of covariates (X) is rank-deficient. Without seeing the actual code/data it is unfortunately hard to pinpoint the exact reason.

**Comment by vrodriguezf** [comment]
Thank you for your answer!

I will try to prepare a reproducible chunk of code. Regarding the rank-deficient covariate matrix, that's very interesting. How can I check that property?

**Comment by helske** [comment]
Sorry, I missed your question about rank deficiency, that is essentially same issue as multicollinearity with linear models. You can check the rank of your covariate matrix with `qr(X)$rank` which can give some hints.

Closed as old.
