### ISSUE TITLE
specifying emission matrix

### ISSUE THREAD

**Issue by UlrikeNaumann** [helske/seqHMM#48]
The build_hmm and build_mhmm functions ask me to specify emission and transition probabilities.
It has the nice feature, that values specified to 0 persist in the estimation as 0.
In order to deal with identifiability issues, I would additionally like to fix some values  in the emission matrix to be equal.
As example, I would like to force emiss[1,1] = emiss[2,2] and emiss[1,4] = emiss[2,4]
emiss <- matrix(
  c(0.6, 0, 0, 0.4,
    0, 0.6, 0, 0.4,
    0, 0, 1, 0),
  nrow = 3, ncol = 4, byrow = TRUE)

Is there any trick how I could achieve this within build_hmm and build_mhmm?
Due to identifiability issues, it would be very important to be able to do this.
Best wishes, Ulrike

**Comment by helske** [comment]
Currently, this is not supported although I agree that it would be a useful feature. In principle, you could do this with seqHMM already by some manual coding: With the help of the log-likelihood method (`logLik`) you could define your own objective function for numerical optimization routine such as `optim` and use that directly instead of the `fit_model` function. If you look at the source code of `fit_model` you can see similar things done there as well (after `if (global_step || local_step)` line). I understand that this is a bit suboptimal though...

**Comment by UlrikeNaumann** [comment]
Thanks, that's very useful!
