### ISSUE TITLE
Extracting combinations of emitted states

### ISSUE THREAD

**Issue by kyrantgs** [helske/seqHMM#63]
When plotting a directed graph for a multi-channel hidden Markov model, the hidden states are displayed as nodes with slices consisting of combinations of emitted states. The emission probabilities for each of the states in each channel can be found with mc_fit[["model"]][["emission_probs"]][["name_of_channel"]], but I have been unable to find the emission probabilities for the combinations of emitted states. It would be helpful to extract the combinations of emitted states and their associated emission probabilities in order to better understand the composition of the hidden states. Is there a way of doing this that I have missed in the seqHMM documentation? If not, is this a feature that could be developed?

**Comment by helske** [comment]
This is available via `mc_to_sc` function, which combines multichannel model to single channel model.

**Comment by kyrantgs** [comment]
Hi Jouni and thanks for the response.

Could you please confirm if the multi-channel and single channel models are equivalent or does using the single channel model require a re-estimation of the model parameters? And are the proportions of the slices of the combined states in a directed graph equal to the emission probabilities of the combined states in a single channel?

Thanks for your help!

**Comment by helske** [comment]
The models are equivalent under the assumption that the channels are independent given the hidden states, in which case we can just multiply the emission probabilities of different channels. But if this assumption does not hold, re-estimating the single channel model can lead to different results (although in practice with complex models it could happen even under the independence assumption due to the multiple local optima in the likelihood surface). 

Yes, the slices of combined states in the plot are just sums of the corresponding emission probabilities.

**Comment by kyrantgs** [comment]
Ok, all understood. thank you again for your help.
