### ISSUE TITLE
Error in if (em.con$reltol < resEM$change) { : argument is of length zero

### ISSUE THREAD

**Issue by Demi-wlw** [helske/seqHMM#64]
When I fit the MHMM with code `build_mhmm(observations = trans_seq, n_states = n_states)`
`fit_model(init_mhmm, control_em = list(restart = list(times = 10)))`, there is an error occurred `Error in if (em.con$reltol < resEM$change) { : argument is of length zero`. What does it mean and how to solve it?

**Comment by helske** [comment]
This sounds like a bug, but I think I would need a fully reproducible example to track it down, as I don't immediately see how this kind of error could occur.

**Comment by robertladwig** [comment]
I am getting the same error with this example, too:

```
df = data.frame('event_1' = c(2,2,2,2,2),
                'event_2' = c(4,9,5,8,4),
                'event_3' = c(9,4,9,4,8),
                'event_4' = c(8,8,8,9,6),
                'event_5' = c(6,6,4,6,9),
                'event_6' = c(5,1,6,5,1),
                'event_7' = c(1,7,1,1,5),
                'event_8' = c(7,5,7,7,7),
                'event_9' = c(3,3,3,3,3))

pheno_seq <- seqdef(df, start = 1)

sc_initmod <- build_mm(observations = pheno_seq)

sc_fit <- fit_model(sc_initmod, em_step = TRUE, global_step = TRUE, local_step = TRUE, 
                    control_em = list(print_level = 2, restart = list(times = 10, reltol = 1e-20)))

sc_fit$logLik
```
 which produces

```
iter: 1 logLik: -38.901 relative change: 1
Error in if (em.con$reltol < resEM$change) { : argument is of length zero
In addition: There were 11 warnings (use warnings() to see them)
```

**Comment by helske** [comment]
I think the issue stems from the fact that there are zero transitions to or from state 3. If I remove the last sequence from your data everything seems to work fine.

**Comment by helske** [comment]
Actually it is not really a bug, because there is zero transitions from 3, so even though by definition the transition probabilities from each state should sum to one, we don't have any clue for those for state 3. I'll change the function so that it will define such a state absorbing i.e. that the corresponding diagonal element is 1.

Running the above example with `sc_initmod$transition_probs[3,3]<-1` seems to work for local and global steps, but the EM still does not work properly, likely because within EM algorithm we are dividing by the number of transition from state 3 which is zero.

**Comment by helske** [comment]
This should work now, with the latest github version I get no errors and reasonable results. I'll update the CRAN version soon.
